[2023-12-25T15:10:56.149+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:10:56.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:10:56.169+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:10:56.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:10:56.230+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:10:56.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity'
[2023-12-25T15:10:56.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:10:56.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.121 seconds
[2023-12-25T15:12:12.645+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:12:12.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:12:12.650+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:12:12.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:12:12.803+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:12:12.801+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity'
[2023-12-25T15:12:12.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:12:12.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.190 seconds
[2023-12-25T15:12:42.983+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:12:42.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:12:42.987+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:12:42.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:12:43.009+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:12:43.008+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity'
[2023-12-25T15:12:43.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:12:43.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.050 seconds
[2023-12-25T15:13:13.241+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:13:13.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:13:13.247+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:13:13.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:13:13.264+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:13:13.263+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity'
[2023-12-25T15:13:13.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:13:13.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.050 seconds
[2023-12-25T15:13:43.439+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:13:43.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:13:43.445+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:13:43.445+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:13:43.478+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:13:43.477+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity'
[2023-12-25T15:13:43.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:13:43.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.072 seconds
[2023-12-25T15:14:13.657+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:14:13.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:14:13.660+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:14:13.660+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:14:13.679+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:14:13.678+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:14:13.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:14:13.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.057 seconds
[2023-12-25T15:14:43.859+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:14:43.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:14:43.862+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:14:43.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:14:43.880+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:14:43.879+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:14:43.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:14:43.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.054 seconds
[2023-12-25T15:15:14.057+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:15:14.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:15:14.060+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:15:14.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:15:14.079+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:15:14.078+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:15:14.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:15:14.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.054 seconds
[2023-12-25T15:15:44.252+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:15:44.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:15:44.257+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:15:44.256+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:15:44.282+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:15:44.281+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:15:44.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:15:44.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.063 seconds
[2023-12-25T15:16:14.467+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:16:14.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:16:14.471+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:16:14.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:16:14.489+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:16:14.488+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:16:14.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:16:14.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.054 seconds
[2023-12-25T15:16:44.660+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:16:44.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:16:44.664+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:16:44.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:16:44.683+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:16:44.682+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:16:44.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:16:44.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.048 seconds
[2023-12-25T15:17:14.885+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:17:14.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:17:14.889+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:17:14.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:17:14.909+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:17:14.908+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:17:14.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:17:14.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.058 seconds
[2023-12-25T15:17:45.092+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:17:45.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:17:45.103+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:17:45.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:17:45.142+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:17:45.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:17:45.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:17:45.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.108 seconds
[2023-12-25T15:18:15.350+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:18:15.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:18:15.358+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:18:15.357+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:18:15.391+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:18:15.390+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:18:15.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:18:15.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.079 seconds
[2023-12-25T15:18:45.586+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:18:45.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:18:45.591+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:18:45.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:18:45.613+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:18:45.612+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:18:45.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:18:45.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.059 seconds
[2023-12-25T15:19:15.790+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:19:15.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:19:15.795+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:19:15.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:19:15.818+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:19:15.817+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:19:15.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:19:15.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.059 seconds
[2023-12-25T15:19:45.987+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:19:45.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:19:45.992+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:19:45.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:19:46.017+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:19:46.016+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:19:46.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:19:46.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.061 seconds
[2023-12-25T15:20:16.209+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:20:16.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:20:16.215+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:20:16.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:20:16.248+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:20:16.246+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:20:16.249+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:20:16.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.082 seconds
[2023-12-25T15:20:46.426+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:20:46.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:20:46.434+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:20:46.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:20:46.477+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:20:46.476+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:20:46.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:20:46.540+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.120 seconds
[2023-12-25T15:21:16.704+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:21:16.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:21:16.708+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:21:16.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:21:16.730+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:21:16.729+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:21:16.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:21:16.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.076 seconds
[2023-12-25T15:21:46.940+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:21:46.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:21:46.944+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:21:46.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:21:46.963+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:21:46.962+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:21:46.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:21:47.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.068 seconds
[2023-12-25T15:22:17.191+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:22:17.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:22:17.195+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:22:17.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:22:17.219+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:22:17.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:22:17.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:22:17.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.055 seconds
[2023-12-25T15:22:47.379+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:22:47.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:22:47.386+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:22:47.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:22:47.408+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:22:47.407+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:22:47.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:22:47.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.059 seconds
[2023-12-25T15:23:17.591+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:23:17.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:23:17.598+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:23:17.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:23:17.664+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:23:17.663+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:23:17.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:23:17.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.115 seconds
[2023-12-25T15:23:47.835+0000] {processor.py:161} INFO - Started process (PID=238) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:23:47.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:23:47.840+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:23:47.840+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:23:47.863+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:23:47.861+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:23:47.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:23:47.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.058 seconds
[2023-12-25T15:24:18.048+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:24:18.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:24:18.052+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:24:18.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:24:18.072+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:24:18.071+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:24:18.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:24:18.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.053 seconds
[2023-12-25T15:24:48.233+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:24:48.235+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:24:48.237+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:24:48.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:24:48.256+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:24:48.256+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:24:48.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:24:48.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.054 seconds
[2023-12-25T15:25:18.423+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:25:18.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:25:18.428+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:25:18.428+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:25:18.451+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:25:18.450+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:25:18.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:25:18.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.059 seconds
[2023-12-25T15:25:48.636+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:25:48.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:25:48.640+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:25:48.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:25:48.667+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:25:48.666+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:25:48.667+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:25:48.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.070 seconds
[2023-12-25T15:26:18.843+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:26:18.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:26:18.847+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:26:18.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:26:18.870+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:26:18.869+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:26:18.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:26:18.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.055 seconds
[2023-12-25T15:26:49.037+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:26:49.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:26:49.045+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:26:49.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:26:49.076+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:26:49.075+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:26:49.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:26:49.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.074 seconds
[2023-12-25T15:27:51.029+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:27:51.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:27:51.047+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:27:51.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:27:51.146+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:27:51.145+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:27:51.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:27:51.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.179 seconds
[2023-12-25T15:28:21.267+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:28:21.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:28:21.270+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:28:21.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:28:21.293+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:28:21.292+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:28:21.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:28:21.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.058 seconds
[2023-12-25T15:28:51.525+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:28:51.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:28:51.533+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:28:51.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:28:51.552+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:28:51.551+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:28:51.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:28:51.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.084 seconds
[2023-12-25T15:29:21.759+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:29:21.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:29:21.778+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:29:21.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:29:21.806+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:29:21.806+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:29:21.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:29:21.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.082 seconds
[2023-12-25T15:29:52.026+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:29:52.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:29:52.031+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:29:52.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:29:52.056+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:29:52.053+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:29:52.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:29:52.091+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.070 seconds
[2023-12-25T15:30:22.916+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:30:22.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:30:22.921+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:30:22.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:30:22.949+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:30:22.948+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:30:22.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:30:22.976+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.065 seconds
[2023-12-25T15:41:11.875+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:41:11.877+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:41:11.881+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:41:11.880+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:41:11.981+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:41:11.980+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:41:11.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:41:12.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.147 seconds
[2023-12-25T15:41:42.183+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:41:42.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:41:42.193+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:41:42.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:41:42.226+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:41:42.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:41:42.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:41:42.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.072 seconds
[2023-12-25T15:42:12.426+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:42:12.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:42:12.433+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:42:12.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:42:12.459+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:42:12.458+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:42:12.460+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:42:12.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.064 seconds
[2023-12-25T15:42:42.648+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:42:42.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:42:42.653+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:42:42.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:42:42.684+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:42:42.683+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:42:42.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:42:42.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.112 seconds
[2023-12-25T15:43:12.915+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:43:12.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:43:12.920+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:43:12.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:43:12.943+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:43:12.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:43:12.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:43:12.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.063 seconds
[2023-12-25T15:43:43.120+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:43:43.120+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:43:43.123+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:43:43.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:43:43.145+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:43:43.145+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:43:43.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:43:43.182+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.068 seconds
[2023-12-25T15:44:13.333+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:44:13.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:44:13.339+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:44:13.339+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:44:13.361+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:44:13.360+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:44:13.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:44:13.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.059 seconds
[2023-12-25T15:44:43.542+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:44:43.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:44:43.545+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:44:43.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:44:43.566+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:44:43.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:44:43.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:44:43.587+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.049 seconds
[2023-12-25T15:45:13.750+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:45:13.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:45:13.755+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:45:13.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:45:13.780+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:45:13.779+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:45:13.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:45:13.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.065 seconds
[2023-12-25T15:45:43.960+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:45:43.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:45:43.966+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:45:43.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:45:43.985+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:45:43.984+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:45:43.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:45:44.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.065 seconds
[2023-12-25T15:46:14.223+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:46:14.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:46:14.228+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:46:14.227+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:46:14.251+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:46:14.250+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:46:14.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:46:14.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.085 seconds
[2023-12-25T15:46:44.468+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:46:44.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:46:44.471+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:46:44.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:46:44.489+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:46:44.489+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:46:44.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:46:44.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.047 seconds
[2023-12-25T15:47:14.671+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:47:14.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:47:14.680+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:47:14.680+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:47:14.708+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:47:14.707+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:47:14.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:47:14.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.071 seconds
[2023-12-25T15:47:44.880+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:47:44.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:47:44.884+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:47:44.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:47:44.917+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:47:44.916+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:47:44.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:47:44.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.101 seconds
[2023-12-25T15:48:15.136+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:15.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:48:15.141+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:48:15.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:15.162+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:48:15.161+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/s3_redshift.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/s3_redshift.py", line 10, in <module>
    from udacity.common import sql_statements
ModuleNotFoundError: No module named 'udacity.common'
[2023-12-25T15:48:15.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:15.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.059 seconds
[2023-12-25T15:48:22.179+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:22.181+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:48:22.184+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:48:22.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:22.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:22.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.074 seconds
[2023-12-25T15:48:52.413+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:52.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:48:52.417+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:48:52.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:52.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:48:52.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.043 seconds
[2023-12-25T15:49:22.606+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:49:22.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:49:22.609+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:49:22.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:49:22.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:49:22.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.042 seconds
[2023-12-25T15:49:52.803+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:49:52.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:49:52.806+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:49:52.806+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:49:52.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:49:52.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.047 seconds
[2023-12-25T15:50:23.009+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:50:23.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:50:23.013+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:50:23.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:50:23.033+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:50:23.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.046 seconds
[2023-12-25T15:50:53.204+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:50:53.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:50:53.209+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:50:53.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:50:53.226+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:50:53.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.044 seconds
[2023-12-25T15:51:23.403+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:51:23.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:51:23.409+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:51:23.408+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:51:23.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:51:23.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.048 seconds
[2023-12-25T15:51:53.631+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:51:53.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:51:53.635+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:51:53.634+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:51:53.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:51:53.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.060 seconds
[2023-12-25T15:52:23.863+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:52:23.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:52:23.868+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:52:23.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:52:23.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:52:23.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.057 seconds
[2023-12-25T15:52:54.077+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:52:54.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:52:54.081+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:52:54.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:52:54.102+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:52:54.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.048 seconds
[2023-12-25T15:53:24.289+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:53:24.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:53:24.309+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:53:24.309+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:53:24.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:53:24.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.098 seconds
[2023-12-25T15:53:54.583+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:53:54.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:53:54.587+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:53:54.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:53:54.607+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:53:54.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.048 seconds
[2023-12-25T15:54:24.801+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:54:24.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:54:24.810+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:54:24.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:54:24.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:54:24.859+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.066 seconds
[2023-12-25T15:54:55.004+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:54:55.008+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:54:55.011+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:54:55.011+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:54:55.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:54:55.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.064 seconds
[2023-12-25T15:55:25.208+0000] {processor.py:161} INFO - Started process (PID=266) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:55:25.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:55:25.216+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:55:25.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:55:25.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:55:25.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.056 seconds
[2023-12-25T15:55:55.413+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:55:55.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:55:55.418+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:55:55.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:55:55.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:55:55.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.046 seconds
[2023-12-25T15:56:25.616+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:56:25.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:56:25.622+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:56:25.622+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:56:25.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:56:25.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.075 seconds
[2023-12-25T15:56:55.856+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:56:55.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:56:55.862+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:56:55.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:56:55.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:56:55.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.063 seconds
[2023-12-25T15:57:26.068+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:57:26.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:57:26.075+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:57:26.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:57:26.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:57:26.132+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.071 seconds
[2023-12-25T15:57:56.304+0000] {processor.py:161} INFO - Started process (PID=308) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:57:56.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:57:56.320+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:57:56.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:57:56.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:57:56.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.107 seconds
[2023-12-25T15:58:26.559+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:58:26.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:58:26.563+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:58:26.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:58:26.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:58:26.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.043 seconds
[2023-12-25T15:58:56.739+0000] {processor.py:161} INFO - Started process (PID=325) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:58:56.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:58:56.744+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:58:56.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:58:56.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:58:56.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.043 seconds
[2023-12-25T15:59:26.915+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:59:26.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:59:26.919+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:59:26.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:59:26.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:59:26.992+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.082 seconds
[2023-12-25T15:59:57.141+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:59:57.143+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T15:59:57.146+0000] {logging_mixin.py:188} INFO - [2023-12-25T15:59:57.145+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:59:57.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T15:59:57.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.064 seconds
[2023-12-25T16:00:27.361+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:00:27.363+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:00:27.367+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:00:27.366+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:00:27.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:00:27.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.083 seconds
[2023-12-25T16:00:57.503+0000] {processor.py:161} INFO - Started process (PID=357) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:00:57.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:00:57.507+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:00:57.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:00:57.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:00:57.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.067 seconds
[2023-12-25T16:01:27.731+0000] {processor.py:161} INFO - Started process (PID=365) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:01:27.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:01:27.735+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:01:27.735+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:01:27.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:01:27.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.048 seconds
[2023-12-25T16:01:57.939+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:01:57.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:01:57.944+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:01:57.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:01:57.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:01:57.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.044 seconds
[2023-12-25T16:02:03.355+0000] {processor.py:161} INFO - Started process (PID=375) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:02:03.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:02:03.359+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:02:03.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:02:03.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:02:03.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.060 seconds
[2023-12-25T16:02:33.560+0000] {processor.py:161} INFO - Started process (PID=383) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:02:33.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:02:33.565+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:02:33.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:02:33.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:02:33.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.063 seconds
[2023-12-25T16:03:03.772+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:03:03.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:03:03.783+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:03:03.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:03:03.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:03:03.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.086 seconds
[2023-12-25T16:03:34.007+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:03:34.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:03:34.012+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:03:34.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:03:34.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:03:34.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.049 seconds
[2023-12-25T16:04:04.166+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:04:04.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:04:04.173+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:04:04.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:04:04.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:04:04.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.063 seconds
[2023-12-25T16:04:34.442+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:04:34.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:04:34.449+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:04:34.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:04:34.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:04:34.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.082 seconds
[2023-12-25T16:05:04.986+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:05:05.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:05:05.007+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:05:05.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:05:05.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:05:05.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.151 seconds
[2023-12-25T16:05:35.298+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:05:35.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:05:35.302+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:05:35.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:05:35.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:05:35.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.043 seconds
[2023-12-25T16:06:05.509+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:06:05.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:06:05.517+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:06:05.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:06:05.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:06:05.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.072 seconds
[2023-12-25T16:06:35.757+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:06:35.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/s3_redshift.py for tasks to queue
[2023-12-25T16:06:35.761+0000] {logging_mixin.py:188} INFO - [2023-12-25T16:06:35.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:06:35.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/s3_redshift.py
[2023-12-25T16:06:35.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/s3_redshift.py took 0.053 seconds
