[2023-12-26T07:22:49.791+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: custom_operators_legacy.load_trips_from_s3_to_redshift scheduled__2018-01-01T00:00:00+00:00 [queued]>
[2023-12-26T07:22:49.803+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: custom_operators_legacy.load_trips_from_s3_to_redshift scheduled__2018-01-01T00:00:00+00:00 [queued]>
[2023-12-26T07:22:49.804+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2023-12-26T07:22:49.819+0000] {taskinstance.py:2192} INFO - Executing <Task(S3ToRedshiftOperator): load_trips_from_s3_to_redshift> on 2018-01-01 00:00:00+00:00
[2023-12-26T07:22:49.825+0000] {standard_task_runner.py:60} INFO - Started process 13441 to run task
[2023-12-26T07:22:49.830+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'custom_operators_legacy', 'load_trips_from_s3_to_redshift', 'scheduled__2018-01-01T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/production/production.py', '--cfg-path', '/tmp/tmpl1xl7476']
[2023-12-26T07:22:49.831+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask load_trips_from_s3_to_redshift
[2023-12-26T07:22:49.884+0000] {task_command.py:423} INFO - Running <TaskInstance: custom_operators_legacy.load_trips_from_s3_to_redshift scheduled__2018-01-01T00:00:00+00:00 [running]> on host d3aa51350085
[2023-12-26T07:22:49.971+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='custom_operators_legacy' AIRFLOW_CTX_TASK_ID='load_trips_from_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2018-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-01-01T00:00:00+00:00'
[2023-12-26T07:22:49.980+0000] {s3_to_redshift.py:44} INFO - Clearing data from destination Redshift table
[2023-12-26T07:22:49.987+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2023-12-26T07:22:50.040+0000] {sql.py:432} INFO - Running statement: DELETE FROM trips, parameters: None
[2023-12-26T07:22:50.802+0000] {sql.py:441} INFO - Rows affected: 0
[2023-12-26T07:22:51.794+0000] {s3_to_redshift.py:47} INFO - Copying data from S3 to Redshift
[2023-12-26T07:22:51.795+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.795+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.796+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.796+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.797+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.797+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.798+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.798+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.798+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.799+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.799+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.799+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-12-26T07:22:51.812+0000] {base.py:83} INFO - Using connection ID 'redshift' for task execution.
[2023-12-26T07:22:51.862+0000] {sql.py:432} INFO - Running statement: 
        COPY trips
        FROM 's3://gitongabretton/data-pipelines/divvy/partitioned/2018/1/divvy_trips.csv'
        ACCESS_KEY_ID 'AKIATZS7MBBSL3CADLWH'
        SECRET_ACCESS_KEY '***'
        IGNOREHEADER 1
        DELIMITER ','
    , parameters: None
[2023-12-26T08:05:11.852+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/opt/airflow/plugins/custom_operators/s3_to_redshift.py", line 58, in execute
    redshift.run(formatted_sql)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 437, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
DETAIL:  
  -----------------------------------------------
  error:  S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
  code:      9002
  context:   Listing bucket=gitongabretton prefix=data-pipelines/divvy/partitioned/2018/1/divvy_trips.csv
  query:     409246[child_sequence:1]
  location:  s3_utility.cpp:702
  process:   padbmaster [pid=1073766519]
  -----------------------------------------------


[2023-12-26T08:05:11.864+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=custom_operators_legacy, task_id=load_trips_from_s3_to_redshift, execution_date=20180101T000000, start_date=20231226T072249, end_date=20231226T080511
[2023-12-26T08:05:11.881+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task load_trips_from_s3_to_redshift (S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
DETAIL:  
  -----------------------------------------------
  error:  S3CurlException: Failed to connect to s3.us-east-1.amazonaws.com port 443: Connection timed out, CurlError 28, multiCurlError 0, CanRetry 1, UserError 0
  code:      9002
  context:   Listing bucket=gitongabretton prefix=data-pipelines/divvy/partitioned/2018/1/divvy_trips.csv
  query:     409246[child_sequence:1]
  location:  s3_utility.cpp:702
  process:   padbmaster [pid=1073766519]
  -----------------------------------------------

; 13441)
[2023-12-26T08:05:11.897+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T08:05:11.929+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
